version: "3.9"

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: p@ssw0rd
            MYSQL_DATABASE: spring_batch
        volumes:
            - ./data:/var/lib/mysql
            - ./logs:/var/log/mysql
        ports:
            - 3306:3306
        expose:
            - 3306